# Database Configuration
db.host=127.0.0.1
db.port=5432
db.user=postgres
db.pass=root
db.name=mapper

# WAL Configuration
wal.archive_src=E:\pg_cron\wal_archive\
wal.archive_dest=E:\pg_cron\pg_cron\backups\incremental\

# Backup Paths
full_backup_path=/backups/full/
incremental_backup_path=/backups/incremental/
